name: CI/CD PIPELINE
on:
 push:
  branches:
   - main
jobs: 
 build: 
  name: Build Application
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - name: Installation python
   - uses: actions/setup-python@v5
