name: CI/CD PIPELINE
on:
 push:
  branches:
   - main
jobs: 
 build: 
  name: Build Application
  runs-on: ubuntu-latest
  steps: 
   - name: verification du repo
   - uses: actions/checkout@v4
   - name: installation de nodejs
   - uses: actions/setup-python@v5
  
